HOST: http://sac-walmart.coopera-csc.com/api/v1/

--- Coopera API V1 ---
--
Coopera Ticket Resource
The following is a section of resources related to the ticket services in Coopera
--

-- Service Request --
Count de tickets por pedido
GET /service_requests/count.json?numero_do_pedido={orderIds}
< 200
< Content-Type: application/json
{
  "74":0,
  "75":0,
  "20002335":1,
  "76":0
}

Consulta pelo id
GET /service_requests/{ticketId}.json
< 200
< Content-Type: application/json
{
  "id":1,
  "status":"open",
  "created_at": "2013-06-24T15:33:20-03:00",
  "form": {
    "4": {
    "numero_do_pedido": 74,
    "numero_do_cliente": "123",
    "tipo_da_solicitacao": "PEDIDO",
    "entregas": [
        {
          "0": "7401",
          "1": "74",
          "2": "123"
        },
        {
          "0": "7401",
          "1": "74",
          "2": "124"
        },
        {
          "0": "7402",
          "1": "74"
        }
      ],
      "items": [
        {
          "0": "123",
          "1": "celular",
          "2": "teste",
          "3": "7401"
        },
        {
          "0": "124",
          "1": "tv",
          "2": "teste",
          "3": "7401"
        },
        {
          "0": "125",
          "1": "garantia",
          "2": "teste",
          "3": "7402"
        }
      ]
    }
  },
  "author": {
  "email": "jmartins@wal-mart.com.br"
  },
  "customer": {
  "email": "jmartins@wal-mart.com.br"
  },
  "requestable_service": {
    "id": 8,
    "name": "Entrega"
  }
}

Cria um novo service request
POST /service_requests.json
> Content-Type: application/json
{
  "service_request": {
    "form": {
      "4": {
        "numero_do_pedido": 74,
        "numero_do_cliente": "11784267260",
        "tipo_da_solicitacao": "PEDIDO"
      }
    },
    "author": {
      "email": "jmartins@wal-mart.com.br"
    },
    "customer": {
      "email": "jmartins@wal-mart.com.br"
    },
    "requestable_service": {
      "id": 7
    }
  }
}
< 201
< Content-Type: application/json
{
  "id":1,
  "status":"open",
  "created_at": "2013-06-24T15:33:20-03:00",
  "form": {
    "4": {
    "numero_do_pedido": 74,
    "numero_do_cliente": "123",
    "tipo_da_solicitacao": "PEDIDO"
    }
  },
  "author": {
  "email": "jmartins@wal-mart.com.br"
  },
  "customer": {
  "email": "jmartins@wal-mart.com.br"
  },
  "requestable_service": {
    "id": 8,
    "name": "Entrega"
  }
}

Reabertura de ticket
PUT /service_requests/{ticketId}/restart
> Content-Type: application/json
{
  "author": {
    "nickname": "anUser"
  },
  "comment": "This is a description!!"
}
< 200
< Content-Type: application/json
{
  "id":1,
  "status":"open",
  "created_at": "2013-06-24T15:33:20-03:00",
  "form": {
    "4": {
    "numero_do_pedido": 74,
    "tipo_da_solicitacao": "PEDIDO"
    }
  },
  "author": {
  "email": "jmartins@wal-mart.com.br"
  },
  "customer": {
  "email": "jmartins@wal-mart.com.br"
  },
  "requestable_service": {
    "id": 8,
    "name": "Entrega"
  }
}

Cancelamento de ticket
PUT /service_requests/{ticketId}/cancel
> Content-Type: application/json
{
  "author": {
    "nickname": "anUser"
  },
  "comment": "This is a description!!"
}
< 200
< Content-Type: application/json
{
  "id":1,
  "status":"canceled",
  "created_at": "2013-06-24T15:33:20-03:00",
  "form": {
    "4": {
    "numero_do_pedido": 74,
    "tipo_da_solicitacao": "PEDIDO"
    }
  },
  "author": {
  "email": "jmartins@wal-mart.com.br"
  },
  "customer": {
  "email": "jmartins@wal-mart.com.br"
  },
  "requestable_service": {
    "id": 8,
    "name": "Entrega"
  }
}

Cria um novo comentario
POST /service_requests/{ticketId}/comments.json
> Content-Type: application/json
{
  "comment": {
    "text": "test",
    "author": {
      "email": "wellington.pinheiro@gmail.com"
    },
    "tags": ["INCOMING_CALL"]
  }
}
< 201
< Content-Type: application/json
{
  "id": "12345",
  "author": {
    "email": "wellington.pinheiro@gmail.com"
  },
  "text": "test",
  "created_at":"2013-06-28T08:30:39-03:00",
  "tags":["INCOMING_CALL"]
}

-- JSON Schema Validations --
POST /service_requests/{ticketId}/comments.json
{
  "type": "object", "required": true,
    "properties": {
      "comment": {
        "type": "object", "required": true,
        "properties": {
          "text": {"type": "string"},
      "tags": {"type": "array", "items": {"type": "string"}},
      "author": {"type": "object", "required": true,
            "properties": { "email": {"type": "string"} }
          }
            
        }
      }
    }
}

-- Requestable Service --
Recupera service request por id
GET /requestable_services/{id}.json
< 200
< Content-Type: application/json
{
    "id": 7,
    "name": "Atraso na entrega",
    "description": "teste",
    "version": 1,
    "company": {
        "company": {
            "created_at": "2013-04-09T10:19:39-03:00",
            "id": 1,
            "inactivated_at": null,
            "name": "Walmart",
            "updated_at": "2013-04-09T10:19:39-03:00"
        }
    },
    "status": "published",
    "created_at": "2013-06-24T15:33:20-03:00",
    "updated_at": "2013-06-24T15:33:20-03:00",
    "sla": null,
    "sla_version": null,
    "service_category": {
        "id": 2,
        "name": "Entrega",
        "ancestry": null,
        "description": null
    },
    "execution_team": {
        "id": 3,
        "name": "Back Office"
    },
    "responsible_team": {
        "id": 3,
        "name": "Back Office"
    },
    "forms": [
        {
            "form": {
                "id": 4,
                "data": [
                    {
                        "other": "Outros",
                        "type": "radio",
                        "name": "field13722638704153",
                        "label": "Tipo da solicitação",
                        "options": [
                            "PEDIDO",
                            "CLIENTE"
                        ],
                        "required": false,
                        "position": 0
                    },
                    {
                        "other": "Outros",
                        "type": "text",
                        "name": "field137210506062410",
                        "label": "Nome do Cliente",
                        "placeholder": "texto de ajuda",
                        "position": 1
                    },
                    {
                        "other": "Outros",
                        "type": "number",
                        "name": "field13721048557414",
                        "label": "Número do Cliente",
                        "position": 2
                    },
                    {
                        "other": "Outros",
                        "type": "number",
                        "name": "field13720960963763",
                        "label": "Número do Pedido",
                        "position": 3
                    },
                    {
                        "other": "Outros",
                        "type": "datetime",
                        "name": "field13721052678636",
                        "label": "Data do pedido",
                        "position": 4
                    },
                    {
                        "other": "Outros",
                        "type": "table",
                        "name": "field137209613567910",
                        "label": "Entrega",
                        "columns": [
                            "Entrega",
                            "Status da Entrega",
                            "Cod do Item",
                            "Descrição do item",
                            "Quantidade",
                            "Valor unitario",
                            "Valor total",
                            "Nota Fiscal",
                            "Filial",
                            "Transportadora"
                        ],
                        "position": 5
                    }
                ]
            }
        }
    ]
}
