HOST: http://sac-walmart.coopera-csc.com/api/v1/

--- Coopera API V1 ---
--
Coopera Ticket Resource
The following is a section of resources related to the ticket services in Coopera
--

GET /service_requests/count.json?numero_do_pedido={orderIds}
< 200
< Content-Type: application/json
{
  "74":0,
  "75":0,
  "76":0
}